exec-once = hyprlock
exec-once = waybar
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = awww-daemon
exec-once = /usr/bin/pypr
exec-once = hypridle
exec-once = hyprsunset
exec-once = hyprpolkitagent
exec-once = awww img ~/arch/wallpapers/DP-2.jpg -o DP-2 --resize crop
exec-once = awww img ~/arch/wallpapers/main.jpg -o HDMI-A-1
exec-once = awww img ~/arch/wallpapers/main.jpg -o eDP-2
