hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("/usr/bin/pypr")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("awww img ~/arch/wallpapers/DP-2.jpg -o DP-2 --resize crop")
    hl.exec_cmd("awww img ~/arch/wallpapers/main.jpg -o HDMI-A-1")
    hl.exec_cmd("awww img ~/arch/wallpapers/main.jpg -o eDP-2")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal")
end)
