source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/looks.conf

input {
  kb_layout=us
  follow_mouse=1
  repeat_rate=35
  repeat_delay=250
  natural_scroll=no
  accel_profile=adaptive
  sensitivity=0.0

  touchpad {
    natural_scroll=yes
    tap-to-click=no
    drag_lock=yes
    clickfinger_behavior=yes
    middle_button_emulation=yes
    disable_while_typing=no
  }
}

gesture = 3, horizontal, workspace
