$accent = #ff79c6
$surface0 = #282a36
$text = #000000
$red = #ff5555
$yellow = #ffbb00
$FAIL = "Incorrect password"

# General settings
general {
    hide_cursor = true
}

# Background widget
background {
    path = ~/.arch/dots/wallpapers/main.jpg # Path to the image
    color = rgba(25, 20, 20, 1.0) # Fallback color
    blur_passes = 1          # Number of blur passes
    blur_size = 7            # Size of the blur effect
}

input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <i>Enter password</i>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}
