general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 120  # 10 minutes idle
    on-timeout = loginctl lock-session
}

listener {
    timeout = 300  # 15 minutes idle
    on-timeout = systemctl suspend
}