general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 60
    on-timeout = brightnessctl -d amdgpu_bl2 -s s 5%
    on-resume = brightnessctl -d amdgpu_bl2 -r
}

listener {
    timeout = 240
    on-timeout = systemctl suspend
}