general {
  gaps_in=6
  gaps_out=6
  border_size=2
  col.active_border=rgb(a3a3a3)
  layout=dwindle
}

decoration {
  rounding=10
  blur {
      enabled = true
      size = 3
      passes = 1 # More passes = better quality, higher GPU usage
      new_optimizations = true # Highly recommended for performance
  }
}

animations {
  enabled=1
}
